/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgotPassword'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardQueueRouteImport } from './routes/_dashboard/queue'
import { Route as DashboardReportRouteImport } from './routes/_dashboard/report'
import { Route as DashboardTechniciansRouteImport } from './routes/_dashboard/technicians'
import { Route as DashboardAdminAuditRouteImport } from './routes/_dashboard/admin/audit'
import { Route as DashboardAdminUsersRouteImport } from './routes/_dashboard/admin/users'
import { Route as DashboardAppointmentsIndexRouteImport } from './routes/_dashboard/appointments/index'
import { Route as DashboardAppointmentsNewRouteImport } from './routes/_dashboard/appointments/new'
import { Route as DashboardTicketsIndexRouteImport } from './routes/_dashboard/tickets/index'
import { Route as DashboardTicketsTicketIdRouteImport } from './routes/_dashboard/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportRoute = DashboardReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTechniciansRoute = DashboardTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminAuditRoute = DashboardAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsIndexRoute =
  DashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppointmentsNewRoute =
  DashboardAppointmentsNewRouteImport.update({
    id: '/appointments/new',
    path: '/appointments/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTicketsIndexRoute = DashboardTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsTicketIdRoute =
  DashboardTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/profile': typeof DashboardProfileRoute
  '/queue': typeof DashboardQueueRoute
  '/report': typeof DashboardReportRoute
  '/technicians': typeof DashboardTechniciansRoute
  '/admin/audit': typeof DashboardAdminAuditRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/appointments/new': typeof DashboardAppointmentsNewRoute
  '/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/appointments/': typeof DashboardAppointmentsIndexRoute
  '/tickets/': typeof DashboardTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/profile': typeof DashboardProfileRoute
  '/queue': typeof DashboardQueueRoute
  '/report': typeof DashboardReportRoute
  '/technicians': typeof DashboardTechniciansRoute
  '/admin/audit': typeof DashboardAdminAuditRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/appointments/new': typeof DashboardAppointmentsNewRoute
  '/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/appointments': typeof DashboardAppointmentsIndexRoute
  '/tickets': typeof DashboardTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/forgotPassword': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/queue': typeof DashboardQueueRoute
  '/_dashboard/report': typeof DashboardReportRoute
  '/_dashboard/technicians': typeof DashboardTechniciansRoute
  '/_dashboard/admin/audit': typeof DashboardAdminAuditRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/_dashboard/appointments/new': typeof DashboardAppointmentsNewRoute
  '/_dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/_dashboard/appointments/': typeof DashboardAppointmentsIndexRoute
  '/_dashboard/tickets/': typeof DashboardTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/queue'
    | '/report'
    | '/technicians'
    | '/admin/audit'
    | '/admin/users'
    | '/appointments/new'
    | '/tickets/$ticketId'
    | '/appointments/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/queue'
    | '/report'
    | '/technicians'
    | '/admin/audit'
    | '/admin/users'
    | '/appointments/new'
    | '/tickets/$ticketId'
    | '/appointments'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/forgotPassword'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_dashboard/dashboard'
    | '/_dashboard/profile'
    | '/_dashboard/queue'
    | '/_dashboard/report'
    | '/_dashboard/technicians'
    | '/_dashboard/admin/audit'
    | '/_dashboard/admin/users'
    | '/_dashboard/appointments/new'
    | '/_dashboard/tickets/$ticketId'
    | '/_dashboard/appointments/'
    | '/_dashboard/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/queue': {
      id: '/_dashboard/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/report': {
      id: '/_dashboard/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof DashboardReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/technicians': {
      id: '/_dashboard/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof DashboardTechniciansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/audit': {
      id: '/_dashboard/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof DashboardAdminAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/appointments/': {
      id: '/_dashboard/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof DashboardAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/appointments/new': {
      id: '/_dashboard/appointments/new'
      path: '/appointments/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof DashboardAppointmentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tickets/': {
      id: '/_dashboard/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof DashboardTicketsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tickets/$ticketId': {
      id: '/_dashboard/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof DashboardTicketsTicketIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardReportRoute: typeof DashboardReportRoute
  DashboardTechniciansRoute: typeof DashboardTechniciansRoute
  DashboardAdminAuditRoute: typeof DashboardAdminAuditRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAppointmentsNewRoute: typeof DashboardAppointmentsNewRoute
  DashboardTicketsTicketIdRoute: typeof DashboardTicketsTicketIdRoute
  DashboardAppointmentsIndexRoute: typeof DashboardAppointmentsIndexRoute
  DashboardTicketsIndexRoute: typeof DashboardTicketsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardReportRoute: DashboardReportRoute,
  DashboardTechniciansRoute: DashboardTechniciansRoute,
  DashboardAdminAuditRoute: DashboardAdminAuditRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAppointmentsNewRoute: DashboardAppointmentsNewRoute,
  DashboardTicketsTicketIdRoute: DashboardTicketsTicketIdRoute,
  DashboardAppointmentsIndexRoute: DashboardAppointmentsIndexRoute,
  DashboardTicketsIndexRoute: DashboardTicketsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
