/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}/index'
import { Route as Char123LangChar125DashboardRouteImport } from './routes/{-$lang}/_dashboard'
import { Route as Char123LangChar125ForgotPasswordRouteImport } from './routes/{-$lang}/forgotPassword'
import { Route as Char123LangChar125LoginRouteImport } from './routes/{-$lang}/login'
import { Route as Char123LangChar125RegisterRouteImport } from './routes/{-$lang}/register'
import { Route as Char123LangChar125ResetPasswordRouteImport } from './routes/{-$lang}/reset-password'
import { Route as Char123LangChar125DashboardDashboardRouteImport } from './routes/{-$lang}/_dashboard/dashboard'
import { Route as Char123LangChar125DashboardProfileRouteImport } from './routes/{-$lang}/_dashboard/profile'
import { Route as Char123LangChar125DashboardQueueRouteImport } from './routes/{-$lang}/_dashboard/queue'
import { Route as Char123LangChar125DashboardReportRouteImport } from './routes/{-$lang}/_dashboard/report'
import { Route as Char123LangChar125DashboardTechniciansRouteImport } from './routes/{-$lang}/_dashboard/technicians'
import { Route as Char123LangChar125DashboardAdminAuditRouteImport } from './routes/{-$lang}/_dashboard/admin/audit'
import { Route as Char123LangChar125DashboardAdminUsersRouteImport } from './routes/{-$lang}/_dashboard/admin/users'
import { Route as Char123LangChar125DashboardAppointmentsIndexRouteImport } from './routes/{-$lang}/_dashboard/appointments/index'
import { Route as Char123LangChar125DashboardAppointmentsNewRouteImport } from './routes/{-$lang}/_dashboard/appointments/new'
import { Route as Char123LangChar125DashboardTicketsIndexRouteImport } from './routes/{-$lang}/_dashboard/tickets/index'
import { Route as Char123LangChar125DashboardTicketsTicketIdRouteImport } from './routes/{-$lang}/_dashboard/tickets/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/{-$lang}/',
  path: '/{-$lang}/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125DashboardRoute =
  Char123LangChar125DashboardRouteImport.update({
    id: '/{-$lang}/_dashboard',
    path: '/{-$lang}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125ForgotPasswordRoute =
  Char123LangChar125ForgotPasswordRouteImport.update({
    id: '/{-$lang}/forgotPassword',
    path: '/{-$lang}/forgotPassword',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125LoginRoute = Char123LangChar125LoginRouteImport.update({
  id: '/{-$lang}/login',
  path: '/{-$lang}/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125RegisterRoute =
  Char123LangChar125RegisterRouteImport.update({
    id: '/{-$lang}/register',
    path: '/{-$lang}/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125ResetPasswordRoute =
  Char123LangChar125ResetPasswordRouteImport.update({
    id: '/{-$lang}/reset-password',
    path: '/{-$lang}/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LangChar125DashboardDashboardRoute =
  Char123LangChar125DashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardProfileRoute =
  Char123LangChar125DashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardQueueRoute =
  Char123LangChar125DashboardQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardReportRoute =
  Char123LangChar125DashboardReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardTechniciansRoute =
  Char123LangChar125DashboardTechniciansRouteImport.update({
    id: '/technicians',
    path: '/technicians',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardAdminAuditRoute =
  Char123LangChar125DashboardAdminAuditRouteImport.update({
    id: '/admin/audit',
    path: '/admin/audit',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardAdminUsersRoute =
  Char123LangChar125DashboardAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardAppointmentsIndexRoute =
  Char123LangChar125DashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardAppointmentsNewRoute =
  Char123LangChar125DashboardAppointmentsNewRouteImport.update({
    id: '/appointments/new',
    path: '/appointments/new',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardTicketsIndexRoute =
  Char123LangChar125DashboardTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)
const Char123LangChar125DashboardTicketsTicketIdRoute =
  Char123LangChar125DashboardTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => Char123LangChar125DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{-$lang}': typeof Char123LangChar125DashboardRouteWithChildren
  '/{-$lang}/forgotPassword': typeof Char123LangChar125ForgotPasswordRoute
  '/{-$lang}/login': typeof Char123LangChar125LoginRoute
  '/{-$lang}/register': typeof Char123LangChar125RegisterRoute
  '/{-$lang}/reset-password': typeof Char123LangChar125ResetPasswordRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/dashboard': typeof Char123LangChar125DashboardDashboardRoute
  '/{-$lang}/profile': typeof Char123LangChar125DashboardProfileRoute
  '/{-$lang}/queue': typeof Char123LangChar125DashboardQueueRoute
  '/{-$lang}/report': typeof Char123LangChar125DashboardReportRoute
  '/{-$lang}/technicians': typeof Char123LangChar125DashboardTechniciansRoute
  '/{-$lang}/admin/audit': typeof Char123LangChar125DashboardAdminAuditRoute
  '/{-$lang}/admin/users': typeof Char123LangChar125DashboardAdminUsersRoute
  '/{-$lang}/appointments/new': typeof Char123LangChar125DashboardAppointmentsNewRoute
  '/{-$lang}/tickets/$ticketId': typeof Char123LangChar125DashboardTicketsTicketIdRoute
  '/{-$lang}/appointments/': typeof Char123LangChar125DashboardAppointmentsIndexRoute
  '/{-$lang}/tickets/': typeof Char123LangChar125DashboardTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/forgotPassword': typeof Char123LangChar125ForgotPasswordRoute
  '/{-$lang}/login': typeof Char123LangChar125LoginRoute
  '/{-$lang}/register': typeof Char123LangChar125RegisterRoute
  '/{-$lang}/reset-password': typeof Char123LangChar125ResetPasswordRoute
  '/{-$lang}/dashboard': typeof Char123LangChar125DashboardDashboardRoute
  '/{-$lang}/profile': typeof Char123LangChar125DashboardProfileRoute
  '/{-$lang}/queue': typeof Char123LangChar125DashboardQueueRoute
  '/{-$lang}/report': typeof Char123LangChar125DashboardReportRoute
  '/{-$lang}/technicians': typeof Char123LangChar125DashboardTechniciansRoute
  '/{-$lang}/admin/audit': typeof Char123LangChar125DashboardAdminAuditRoute
  '/{-$lang}/admin/users': typeof Char123LangChar125DashboardAdminUsersRoute
  '/{-$lang}/appointments/new': typeof Char123LangChar125DashboardAppointmentsNewRoute
  '/{-$lang}/tickets/$ticketId': typeof Char123LangChar125DashboardTicketsTicketIdRoute
  '/{-$lang}/appointments': typeof Char123LangChar125DashboardAppointmentsIndexRoute
  '/{-$lang}/tickets': typeof Char123LangChar125DashboardTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{-$lang}/_dashboard': typeof Char123LangChar125DashboardRouteWithChildren
  '/{-$lang}/forgotPassword': typeof Char123LangChar125ForgotPasswordRoute
  '/{-$lang}/login': typeof Char123LangChar125LoginRoute
  '/{-$lang}/register': typeof Char123LangChar125RegisterRoute
  '/{-$lang}/reset-password': typeof Char123LangChar125ResetPasswordRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/_dashboard/dashboard': typeof Char123LangChar125DashboardDashboardRoute
  '/{-$lang}/_dashboard/profile': typeof Char123LangChar125DashboardProfileRoute
  '/{-$lang}/_dashboard/queue': typeof Char123LangChar125DashboardQueueRoute
  '/{-$lang}/_dashboard/report': typeof Char123LangChar125DashboardReportRoute
  '/{-$lang}/_dashboard/technicians': typeof Char123LangChar125DashboardTechniciansRoute
  '/{-$lang}/_dashboard/admin/audit': typeof Char123LangChar125DashboardAdminAuditRoute
  '/{-$lang}/_dashboard/admin/users': typeof Char123LangChar125DashboardAdminUsersRoute
  '/{-$lang}/_dashboard/appointments/new': typeof Char123LangChar125DashboardAppointmentsNewRoute
  '/{-$lang}/_dashboard/tickets/$ticketId': typeof Char123LangChar125DashboardTicketsTicketIdRoute
  '/{-$lang}/_dashboard/appointments/': typeof Char123LangChar125DashboardAppointmentsIndexRoute
  '/{-$lang}/_dashboard/tickets/': typeof Char123LangChar125DashboardTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{-$lang}'
    | '/{-$lang}/forgotPassword'
    | '/{-$lang}/login'
    | '/{-$lang}/register'
    | '/{-$lang}/reset-password'
    | '/{-$lang}/'
    | '/{-$lang}/dashboard'
    | '/{-$lang}/profile'
    | '/{-$lang}/queue'
    | '/{-$lang}/report'
    | '/{-$lang}/technicians'
    | '/{-$lang}/admin/audit'
    | '/{-$lang}/admin/users'
    | '/{-$lang}/appointments/new'
    | '/{-$lang}/tickets/$ticketId'
    | '/{-$lang}/appointments/'
    | '/{-$lang}/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/{-$lang}'
    | '/{-$lang}/forgotPassword'
    | '/{-$lang}/login'
    | '/{-$lang}/register'
    | '/{-$lang}/reset-password'
    | '/{-$lang}/dashboard'
    | '/{-$lang}/profile'
    | '/{-$lang}/queue'
    | '/{-$lang}/report'
    | '/{-$lang}/technicians'
    | '/{-$lang}/admin/audit'
    | '/{-$lang}/admin/users'
    | '/{-$lang}/appointments/new'
    | '/{-$lang}/tickets/$ticketId'
    | '/{-$lang}/appointments'
    | '/{-$lang}/tickets'
  id:
    | '__root__'
    | '/'
    | '/{-$lang}/_dashboard'
    | '/{-$lang}/forgotPassword'
    | '/{-$lang}/login'
    | '/{-$lang}/register'
    | '/{-$lang}/reset-password'
    | '/{-$lang}/'
    | '/{-$lang}/_dashboard/dashboard'
    | '/{-$lang}/_dashboard/profile'
    | '/{-$lang}/_dashboard/queue'
    | '/{-$lang}/_dashboard/report'
    | '/{-$lang}/_dashboard/technicians'
    | '/{-$lang}/_dashboard/admin/audit'
    | '/{-$lang}/_dashboard/admin/users'
    | '/{-$lang}/_dashboard/appointments/new'
    | '/{-$lang}/_dashboard/tickets/$ticketId'
    | '/{-$lang}/_dashboard/appointments/'
    | '/{-$lang}/_dashboard/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123LangChar125DashboardRoute: typeof Char123LangChar125DashboardRouteWithChildren
  Char123LangChar125ForgotPasswordRoute: typeof Char123LangChar125ForgotPasswordRoute
  Char123LangChar125LoginRoute: typeof Char123LangChar125LoginRoute
  Char123LangChar125RegisterRoute: typeof Char123LangChar125RegisterRoute
  Char123LangChar125ResetPasswordRoute: typeof Char123LangChar125ResetPasswordRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/{-$lang}'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/_dashboard': {
      id: '/{-$lang}/_dashboard'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/forgotPassword': {
      id: '/{-$lang}/forgotPassword'
      path: '/{-$lang}/forgotPassword'
      fullPath: '/{-$lang}/forgotPassword'
      preLoaderRoute: typeof Char123LangChar125ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/login': {
      id: '/{-$lang}/login'
      path: '/{-$lang}/login'
      fullPath: '/{-$lang}/login'
      preLoaderRoute: typeof Char123LangChar125LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/register': {
      id: '/{-$lang}/register'
      path: '/{-$lang}/register'
      fullPath: '/{-$lang}/register'
      preLoaderRoute: typeof Char123LangChar125RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/reset-password': {
      id: '/{-$lang}/reset-password'
      path: '/{-$lang}/reset-password'
      fullPath: '/{-$lang}/reset-password'
      preLoaderRoute: typeof Char123LangChar125ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/_dashboard/dashboard': {
      id: '/{-$lang}/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/{-$lang}/dashboard'
      preLoaderRoute: typeof Char123LangChar125DashboardDashboardRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/profile': {
      id: '/{-$lang}/_dashboard/profile'
      path: '/profile'
      fullPath: '/{-$lang}/profile'
      preLoaderRoute: typeof Char123LangChar125DashboardProfileRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/queue': {
      id: '/{-$lang}/_dashboard/queue'
      path: '/queue'
      fullPath: '/{-$lang}/queue'
      preLoaderRoute: typeof Char123LangChar125DashboardQueueRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/report': {
      id: '/{-$lang}/_dashboard/report'
      path: '/report'
      fullPath: '/{-$lang}/report'
      preLoaderRoute: typeof Char123LangChar125DashboardReportRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/technicians': {
      id: '/{-$lang}/_dashboard/technicians'
      path: '/technicians'
      fullPath: '/{-$lang}/technicians'
      preLoaderRoute: typeof Char123LangChar125DashboardTechniciansRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/admin/audit': {
      id: '/{-$lang}/_dashboard/admin/audit'
      path: '/admin/audit'
      fullPath: '/{-$lang}/admin/audit'
      preLoaderRoute: typeof Char123LangChar125DashboardAdminAuditRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/admin/users': {
      id: '/{-$lang}/_dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/{-$lang}/admin/users'
      preLoaderRoute: typeof Char123LangChar125DashboardAdminUsersRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/appointments/': {
      id: '/{-$lang}/_dashboard/appointments/'
      path: '/appointments'
      fullPath: '/{-$lang}/appointments/'
      preLoaderRoute: typeof Char123LangChar125DashboardAppointmentsIndexRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/appointments/new': {
      id: '/{-$lang}/_dashboard/appointments/new'
      path: '/appointments/new'
      fullPath: '/{-$lang}/appointments/new'
      preLoaderRoute: typeof Char123LangChar125DashboardAppointmentsNewRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/tickets/': {
      id: '/{-$lang}/_dashboard/tickets/'
      path: '/tickets'
      fullPath: '/{-$lang}/tickets/'
      preLoaderRoute: typeof Char123LangChar125DashboardTicketsIndexRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
    '/{-$lang}/_dashboard/tickets/$ticketId': {
      id: '/{-$lang}/_dashboard/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/{-$lang}/tickets/$ticketId'
      preLoaderRoute: typeof Char123LangChar125DashboardTicketsTicketIdRouteImport
      parentRoute: typeof Char123LangChar125DashboardRoute
    }
  }
}

interface Char123LangChar125DashboardRouteChildren {
  Char123LangChar125DashboardDashboardRoute: typeof Char123LangChar125DashboardDashboardRoute
  Char123LangChar125DashboardProfileRoute: typeof Char123LangChar125DashboardProfileRoute
  Char123LangChar125DashboardQueueRoute: typeof Char123LangChar125DashboardQueueRoute
  Char123LangChar125DashboardReportRoute: typeof Char123LangChar125DashboardReportRoute
  Char123LangChar125DashboardTechniciansRoute: typeof Char123LangChar125DashboardTechniciansRoute
  Char123LangChar125DashboardAdminAuditRoute: typeof Char123LangChar125DashboardAdminAuditRoute
  Char123LangChar125DashboardAdminUsersRoute: typeof Char123LangChar125DashboardAdminUsersRoute
  Char123LangChar125DashboardAppointmentsNewRoute: typeof Char123LangChar125DashboardAppointmentsNewRoute
  Char123LangChar125DashboardTicketsTicketIdRoute: typeof Char123LangChar125DashboardTicketsTicketIdRoute
  Char123LangChar125DashboardAppointmentsIndexRoute: typeof Char123LangChar125DashboardAppointmentsIndexRoute
  Char123LangChar125DashboardTicketsIndexRoute: typeof Char123LangChar125DashboardTicketsIndexRoute
}

const Char123LangChar125DashboardRouteChildren: Char123LangChar125DashboardRouteChildren =
  {
    Char123LangChar125DashboardDashboardRoute:
      Char123LangChar125DashboardDashboardRoute,
    Char123LangChar125DashboardProfileRoute:
      Char123LangChar125DashboardProfileRoute,
    Char123LangChar125DashboardQueueRoute:
      Char123LangChar125DashboardQueueRoute,
    Char123LangChar125DashboardReportRoute:
      Char123LangChar125DashboardReportRoute,
    Char123LangChar125DashboardTechniciansRoute:
      Char123LangChar125DashboardTechniciansRoute,
    Char123LangChar125DashboardAdminAuditRoute:
      Char123LangChar125DashboardAdminAuditRoute,
    Char123LangChar125DashboardAdminUsersRoute:
      Char123LangChar125DashboardAdminUsersRoute,
    Char123LangChar125DashboardAppointmentsNewRoute:
      Char123LangChar125DashboardAppointmentsNewRoute,
    Char123LangChar125DashboardTicketsTicketIdRoute:
      Char123LangChar125DashboardTicketsTicketIdRoute,
    Char123LangChar125DashboardAppointmentsIndexRoute:
      Char123LangChar125DashboardAppointmentsIndexRoute,
    Char123LangChar125DashboardTicketsIndexRoute:
      Char123LangChar125DashboardTicketsIndexRoute,
  }

const Char123LangChar125DashboardRouteWithChildren =
  Char123LangChar125DashboardRoute._addFileChildren(
    Char123LangChar125DashboardRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123LangChar125DashboardRoute:
    Char123LangChar125DashboardRouteWithChildren,
  Char123LangChar125ForgotPasswordRoute: Char123LangChar125ForgotPasswordRoute,
  Char123LangChar125LoginRoute: Char123LangChar125LoginRoute,
  Char123LangChar125RegisterRoute: Char123LangChar125RegisterRoute,
  Char123LangChar125ResetPasswordRoute: Char123LangChar125ResetPasswordRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
